#' Wrapper function to call bibliometrix's convert2df() for a given set of records
#'
#' @param db_data - list containing 3 elements: file (either a single file or vector with multiple files containing bibliographic records), dbsource (bibliographic source), and format (file format)
#'
#' @return a database featuring all records from the files specified, formatted according to bibliometrix fields
#' @seealso [bibliometrix::convert2df()]
#'
# @export
#'
# @examples
convert2df_wrapper <- function(db_data) {
  bibliometrix_df <- bibliometrix::convert2df(db_data$file,
                                dbsource = db_data$dbsource,
                                format = db_data$format )
  return(bibliometrix_df)
}



#' Function to convert list of database files into db_lists using bibliometrix
#'
#' @param dataset_list - a list of the files in each dataset. Each is a list containing 3 elements: *file* (either a +-pç34yghtsingle file or vector with multiple files containing bibliographic records), *dbsource* (bibliographic source), and *format* (file format)
#' Example: datasets <- list(dimensions = list(file = 'path/to/dimensions.csv', dbsource = 'dimensions', format = 'csv'), scopus = list(file = c('path/to/scopus/1.bib', 'path/to/scopus/2.bib'), dbsource = 'scopus', format = 'bibtex'), wos = list(file = c('path/to/wos/1.bib','path/to/wos/2.bib'), dbsource = 'wos', format = 'bibtex'), 'lens' = list(file = 'path/to/lens.csv', dbsource = 'lens', format = 'csv') )
#'
#'
#' @param n_threads - number of (logical) cores used in the parsing process. By default, uses the number of cores dectected by parallel:detectCores(). Internally, however, this parameter will not exceed the number datasets provided, since going above this threshold would not increase performance.
#'
#'
#' @return a db_list
#' @export
#'
# @examples
bibliometrix_parsing <- function(dataset_list, n_threads = parallel::detectCores() ) {
  n_sets <- length(dataset_list)
  if (n_threads > n_sets) {
    n_threads <- n_sets
  }
  db_list <- parallel::mclapply(dataset_list, function(db_data) convert2df_wrapper(db_data), mc.cores = n_threads )
  return(db_list)
}





#merge_db_list <- function(db_list) {
#  return( dplyr::bind_rows(db_list, .id = 'SET_NAME') )
#}


#' Obtaining a table summary of biblioverlap's matching
#'
#' @param matched_db_list - list of matched dataframes (with UUID column added by biblioverlap)
#'
#' @return a table summary the matching results
#' @importFrom rlang .data
# @export
#'
# @examples
matching_summary_df <- function(matched_db_list) {
  #Getting dataframes
  all_data <- do.call(rbind, matched_db_list) #Saving all data into a single df
  matched_data <-  all_data %>%
    dplyr::filter(duplicated(.data$UUID)) %>% #Filtering only rows with duplicated UUID (docs with match)
    dplyr::distinct(.data$UUID, .keep_all = TRUE) #And then obtaining only one (the first) occurrence of each matched document
  #Getting values
  summary <- list()
  summary$total <- nrow(all_data)
  summary$unique <- nrow(all_data %>% dplyr::distinct(.data$UUID, .keep_all = TRUE))
  summary$duplicates <- summary$total - summary$unique
  summary$matched <- nrow(matched_data)
  summary$unmatched <- summary$unique - summary$matched
  summary$matched_id <- nrow(matched_data %>% dplyr::filter(!is.na(DI)))
  summary$matched_score <- nrow(matched_data %>% dplyr::filter(is.na(DI))) #USES DI column
  summary_df <- data.frame(doc_subset = names(summary), n_docs = unlist(summary), row.names = NULL)
  #return(summary)
  #return(df)
  #Getting dataframe
  categories <- c('total', 'unique/duplicates', 'unique/duplicates', 'unique', 'unique', 'matched', 'matched')
  doc_subset_levels <- c('total',  'duplicates', 'unique', 'unmatched', 'matched',  'matched_id', 'matched_score' )
  final_summary_df <- summary_df %>%
    #tidyr::pivot_longer(cols = dplyr::everything(), names_to = "doc_subset", values_to = "n_docs" ) %>%
    dplyr::mutate("doc_subset" = factor(.data$doc_subset, levels = doc_subset_levels)) %>%
    dplyr::mutate("category" = factor(categories, levels = unique(categories)), .after = .data$doc_subset) %>%
    dplyr::group_by(.data$category) %>%
    dplyr::mutate("perc_inside_category" = round(.data$n_docs / sum(.data$n_docs) * 100, 1))
  return(final_summary_df)
}


#' Obtaining a plot summary of biblioverlap's matching
#'
#' @param matching_summary_df - summary of matching process generated by `matching_summary_df()`
#'
#' @return a barplot summary of the matching results
#'
#' @importFrom rlang .data
# @export
#'
# @examples
matching_summary_plot <- function(matching_summary_df) {
  plot <- matching_summary_df %>%
    ggplot2::ggplot(ggplot2::aes(x = .data$category, y = .data$n_docs, fill = .data$doc_subset)) +
    ggplot2::geom_bar(stat = 'identity', position = 'stack') +
    ggplot2::geom_text(ggplot2::aes(label = paste0(.data$n_docs," (",.data$perc_inside_category,"%)" ) ), position = ggplot2::position_stack(vjust = 0.5))

  return(plot)
}


#' Getting a matching summary (plot and dataframe) of biblioverlap matching results
#'
#' @param internal_db_list - list of matched dataframes used internally by biblioverlap
#'
#' @return a list containing a summary (df and plot) of the matching results
#' @importFrom rlang .data
#' @export
#'
# @examples
get_matching_summary <- function(internal_db_list) {
  summary_df <- matching_summary_df(internal_db_list)
  summary_plot <- matching_summary_plot(summary_df)
  return ( list('df' = summary_df,
                'plot' = summary_plot ) )
}




#' Plotting Venn Diagram based on biblioverlap results
#'
#' @param db_list - list of matched dataframes (with UUID column added by biblioverlap)
#'
#' @return a ggVennDiagram plot
#' @export
#'
# @examples
get_venn_diagram <- function(db_list) {
  uuid <- lapply(db_list, function(db) db$UUID)
  return( ggVennDiagram::ggVennDiagram(uuid) )
}


#' Plotting UpSet plot
#'
#' @param db_list  - list of matched dataframes (with UUID column added by biblioverlap)
#'
#' @return - an UpSet plot
#' @export
#'
# @examples
get_upset_plot <- function(db_list) {
  uuid <- lapply(db_list, function(db) db$UUID)
  upset <- UpSetR::upset(UpSetR::fromList(uuid))
  return( upset )
}

