#' Obtaining a plot summary of biblioverlap's matching
#'
#' @param matching_summary_df - summary of matching process generated by `matching_summary_df()`
#' @param ... - additional arguments passed down to `ggplot2::geom_text()`
#'
#' @return a barplot summary of the matching results
#'
#' @importFrom rlang .data
#' @export
#'
# @examples
plot_matching_summary <- function(matching_summary_df, ...) {
  plot <- matching_summary_df %>%
    ggplot2::ggplot(ggplot2::aes(x = .data$category, y = .data$n_docs, fill = .data$doc_subset)) +
    ggplot2::geom_bar(stat = 'identity', position = 'stack') +
    ggplot2::geom_text(ggplot2::aes(label = paste0(.data$n_docs," (",.data$perc_inside_category,"%)")), position = ggplot2::position_stack(vjust = 0.5), ... )

  return(plot)
}


# Getting a matching summary (plot and dataframe) of biblioverlap matching results
#
# @param internal_db_list - list of matched dataframes used internally by biblioverlap
#
# @return a list containing a summary (df and plot) of the matching results
# @importFrom rlang .data
# @export
#
# @examples
#get_matching_summary <- function(internal_db_list) {
#  summary_df <- matching_summary_df(internal_db_list)
#  summary_plot <- matching_summary_plot(summary_df)
#  return ( list('df' = summary_df,
#                'plot' = summary_plot ) )
#}


get_uuid_list <- function(db_list) {
  return( lapply(db_list, function(db) db$UUID) )
}


#' Plotting Venn Diagram from biblioverlap results
#'
#' @param db_list - list of matched dataframes (with UUID column added by biblioverlap)
#' @param ... - Additional arguments that can be passed down to [ggVennDiagram::ggVennDiagram()]
#'
#' @return a Venn Diagram
#' @export
#'
# @examples
plot_venn <- function(db_list, ...) {
  uuid <- get_uuid_list(db_list)
  venn <- ggVennDiagram::ggVennDiagram(uuid, ...) +
    ggplot2::scale_fill_gradient(low = "#A7C7E7", high = "#08306B") +
    ggplot2::scale_x_continuous(expand = ggplot2::expansion(mult = .2))
  return ( venn )
}

#plot_summ <- plot_matching_summary(test$summary, size = 5)
#
#plot_mod <- plot_summ +
#  ggplot2::theme(text=ggplot2::element_text(size=15))
#
#
#plot_summ
#
#plot_mod

#' Plotting UpSet plot from biblioverlap results
#'
#' @param db_list - list of matched dataframes (with UUID column added by biblioverlap)
#' @param ... - arguments to be passed down to [UpSetR::upset()]
#'
#' @return a UpSet plot
#' @export
#'
# @examples
plot_upset <- function(db_list, ...) {
  uuid <- get_uuid_list(db_list)
  upset <- UpSetR::upset(UpSetR::fromList(uuid), ...)
  return ( upset )
}


#' Title
#'
#' @param port - port of the application
#' @param max_upload_size - max upload size of documents (in MB) - Default 100
#' @param launch.browser - launch on browser - Default = TRUE
#'
#' @return opens a instance of the biblioverlap UI
#' @export
#'
# @examples
biblioverApp <- function(port = NULL, max_upload_size = 1000, launch.browser = TRUE) {
  options(shiny.maxRequestSize = max_upload_size * 1024 * 1024)
  shiny::shinyAppDir(
    system.file("biblioverApp", package = "biblioverlap"),
    options = list(port = port, launch.browser = launch.browser)
  )
}




